/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerQuizQuestion {
  'question' : string,
  'categoryScores' : Array<bigint>,
  'options' : Array<string>,
}
export interface CareerQuizResult {
  'careerScope' : string,
  'score' : bigint,
  'recommendedStream' : string,
  'suggestedSubjects' : Array<string>,
}
export interface ChatMessage {
  'sender' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Internship {
  'title' : string,
  'duration' : string,
  'link' : string,
  'description' : string,
  'eligibility' : string,
  'company' : string,
}
export interface MockTestQuestion {
  'question' : string,
  'correctAnswer' : bigint,
  'options' : Array<string>,
}
export interface MockTestResult {
  'performanceRating' : string,
  'subject' : string,
  'score' : bigint,
  'correctAnswers' : Array<bigint>,
}
export interface Profile {
  'dateOfBirth' : string,
  'appearance' : { 'dark' : null } |
    { 'light' : null },
  'school' : string,
  'name' : string,
  'language' : string,
  'classYear' : string,
}
export interface Scholarship {
  'title' : string,
  'link' : string,
  'description' : string,
  'eligibility' : string,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllInternships' : ActorMethod<[], Array<Internship>>,
  'getAllScholarships' : ActorMethod<[], Array<Scholarship>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [Profile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCareerQuizQuestions' : ActorMethod<[], Array<CareerQuizQuestion>>,
  'getCareerQuizResult' : ActorMethod<[], [] | [CareerQuizResult]>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getLastMessage' : ActorMethod<[], [] | [ChatMessage]>,
  'getMockTest' : ActorMethod<[string], Array<MockTestQuestion>>,
  'getProfile' : ActorMethod<[], Profile>,
  'getSavedInternships' : ActorMethod<[], [] | [Array<string>]>,
  'getSavedScholarships' : ActorMethod<[], [] | [Array<string>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [Profile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logout' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[Profile], undefined>,
  'saveInternship' : ActorMethod<[string], undefined>,
  'saveProfile' : ActorMethod<[Profile], undefined>,
  'saveScholarship' : ActorMethod<[string], undefined>,
  'sendMessageToChatbot' : ActorMethod<[string], ChatMessage>,
  'submitCareerQuiz' : ActorMethod<[Array<bigint>], CareerQuizResult>,
  'submitMockTest' : ActorMethod<[string, Array<bigint>], MockTestResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];