/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Internship = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Text,
  'company' : IDL.Text,
});
export const Scholarship = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Text,
  'description' : IDL.Text,
  'eligibility' : IDL.Text,
});
export const Profile = IDL.Record({
  'dateOfBirth' : IDL.Text,
  'appearance' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
  'school' : IDL.Text,
  'name' : IDL.Text,
  'language' : IDL.Text,
  'classYear' : IDL.Text,
});
export const CareerQuizQuestion = IDL.Record({
  'question' : IDL.Text,
  'categoryScores' : IDL.Vec(IDL.Nat),
  'options' : IDL.Vec(IDL.Text),
});
export const CareerQuizResult = IDL.Record({
  'careerScope' : IDL.Text,
  'score' : IDL.Nat,
  'recommendedStream' : IDL.Text,
  'suggestedSubjects' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const ChatMessage = IDL.Record({
  'sender' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const MockTestQuestion = IDL.Record({
  'question' : IDL.Text,
  'correctAnswer' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const MockTestResult = IDL.Record({
  'performanceRating' : IDL.Text,
  'subject' : IDL.Text,
  'score' : IDL.Nat,
  'correctAnswers' : IDL.Vec(IDL.Nat),
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllInternships' : IDL.Func([], [IDL.Vec(Internship)], []),
  'getAllScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCareerQuizQuestions' : IDL.Func([], [IDL.Vec(CareerQuizQuestion)], []),
  'getCareerQuizResult' : IDL.Func([], [IDL.Opt(CareerQuizResult)], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getLastMessage' : IDL.Func([], [IDL.Opt(ChatMessage)], ['query']),
  'getMockTest' : IDL.Func([IDL.Text], [IDL.Vec(MockTestQuestion)], []),
  'getProfile' : IDL.Func([], [Profile], ['query']),
  'getSavedInternships' : IDL.Func([], [IDL.Opt(IDL.Vec(IDL.Text))], ['query']),
  'getSavedScholarships' : IDL.Func(
      [],
      [IDL.Opt(IDL.Vec(IDL.Text))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logout' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([Profile], [], []),
  'saveInternship' : IDL.Func([IDL.Text], [], []),
  'saveProfile' : IDL.Func([Profile], [], []),
  'saveScholarship' : IDL.Func([IDL.Text], [], []),
  'sendMessageToChatbot' : IDL.Func([IDL.Text], [ChatMessage], []),
  'submitCareerQuiz' : IDL.Func([IDL.Vec(IDL.Nat)], [CareerQuizResult], []),
  'submitMockTest' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat)],
      [MockTestResult],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Internship = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Text,
    'company' : IDL.Text,
  });
  const Scholarship = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Text,
    'description' : IDL.Text,
    'eligibility' : IDL.Text,
  });
  const Profile = IDL.Record({
    'dateOfBirth' : IDL.Text,
    'appearance' : IDL.Variant({ 'dark' : IDL.Null, 'light' : IDL.Null }),
    'school' : IDL.Text,
    'name' : IDL.Text,
    'language' : IDL.Text,
    'classYear' : IDL.Text,
  });
  const CareerQuizQuestion = IDL.Record({
    'question' : IDL.Text,
    'categoryScores' : IDL.Vec(IDL.Nat),
    'options' : IDL.Vec(IDL.Text),
  });
  const CareerQuizResult = IDL.Record({
    'careerScope' : IDL.Text,
    'score' : IDL.Nat,
    'recommendedStream' : IDL.Text,
    'suggestedSubjects' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const ChatMessage = IDL.Record({
    'sender' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const MockTestQuestion = IDL.Record({
    'question' : IDL.Text,
    'correctAnswer' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const MockTestResult = IDL.Record({
    'performanceRating' : IDL.Text,
    'subject' : IDL.Text,
    'score' : IDL.Nat,
    'correctAnswers' : IDL.Vec(IDL.Nat),
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllInternships' : IDL.Func([], [IDL.Vec(Internship)], []),
    'getAllScholarships' : IDL.Func([], [IDL.Vec(Scholarship)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(Profile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCareerQuizQuestions' : IDL.Func([], [IDL.Vec(CareerQuizQuestion)], []),
    'getCareerQuizResult' : IDL.Func(
        [],
        [IDL.Opt(CareerQuizResult)],
        ['query'],
      ),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getLastMessage' : IDL.Func([], [IDL.Opt(ChatMessage)], ['query']),
    'getMockTest' : IDL.Func([IDL.Text], [IDL.Vec(MockTestQuestion)], []),
    'getProfile' : IDL.Func([], [Profile], ['query']),
    'getSavedInternships' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'getSavedScholarships' : IDL.Func(
        [],
        [IDL.Opt(IDL.Vec(IDL.Text))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(Profile)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logout' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([Profile], [], []),
    'saveInternship' : IDL.Func([IDL.Text], [], []),
    'saveProfile' : IDL.Func([Profile], [], []),
    'saveScholarship' : IDL.Func([IDL.Text], [], []),
    'sendMessageToChatbot' : IDL.Func([IDL.Text], [ChatMessage], []),
    'submitCareerQuiz' : IDL.Func([IDL.Vec(IDL.Nat)], [CareerQuizResult], []),
    'submitMockTest' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat)],
        [MockTestResult],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };